default_language_version:
  rust: latest

repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt --all --check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: lint
        name: lint
        entry: just lint
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: file-lengths
        name: file-lengths
        entry: scripts/check-file-lengths.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
